---
trainer:
  steps: 500
  workers: 8

  tensorboard_name:
  save_freq: 10

  ppo_config:
    optimizer: adam
    optimizer_kwargs:
      lr: 0.0001
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false

    gamma: 0.5
    ppo_steps: 25
    eps: 0.25
    target_kl: 0.01

    value_steps: 25

    entropy_coeff: 0.001
    entropy_decay_time: 100
    min_entropy: 0.001
    use_gpu: false

model:
  input_size: 4
  num_activations: 2
  activation: tanh

  hidden_sizes: !!python/tuple [32, 32]
  separate_value: true

  sigma0: 0.7

  initializer: kaiming_uniform
