---
trainer:
  steps: 500
  workers: 8

  tensorboard_name:
  save_freq: 10

  gamma: 0.95
  ppo_steps: 25
  eps: 0.25
  target_kl: 0.01
  entropy_coeff: 0.1

  use_gpu: false

  ppo_config:
    optimizer: adam
    optimizer_kwargs:
      lr: 0.0001
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false
model:
  input_size: 6
  num_activations: 2
  activation: tanh

  hidden_sizes: !!python/tuple [64, 64]
  separate_value: true

  sigma0: 0.3

  initializer: kaiming_uniform
