---
trainer:
  steps: 500
  workers: 8

  tensorboard_name:
  save_freq: 10

  ppo_config:
    optimizer: adam
    optimizer_kwargs:
      lr: 0.0001
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false

    gamma: 0.9
    eta: 0.5
    gae_lambda: 0.95

    eps: 0.25
    target_kl: 0.03
    entropy_coeff: 0.0
    entropy_decay_time: 100
    min_entropy: 0.0
    value_coeff: 1.0

    ppo_epochs: 5
    minibatch_size: 8192

    use_gpu: false

model:
  input_size:
  num_activations: 2
  activation: tanh

  hidden_sizes: [64, 64, 64]
  separate_value: true

  rays_input_size:

  conv_filters: 2

  sigma0: 0.7

  initializer: kaiming_uniform
